FROM docker.elastic.co/elasticsearch/elasticsearch:8.11.2
RUN elasticsearch-plugin install https://github.com/medcl/elasticsearch-analysis-ik/releases/download/v8.11.2/elasticsearch-analysis-ik-8.11.2.zip
